version: '3'
services:
  DataBase:
    image: mysql
    container_name: DataBase
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    image: jafarsw/real-time-chat
    container_name: final-project
    build: .
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}  
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - DataBase
    volumes:
      - /home/jafar/Desktop/Real_time_Chat_Application:/usr/app:ro
