# version: '3'
# services:
#   DataBase:
#     image: mysql
#     container_name: DataBase
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#       - MYSQL_DATABASE=${DB_NAME}
#     ports:
#       - 3306:3306
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10
  
#   app:
#     image: ghcr.io/jafar-sweity/-docker:$GIT_VERSION
#     container_name: final-project
#     environment:  
#       - PORT=80
#       - DB_HOST=${DB_HOST}
#       - DB_USER=${DB_USER_NAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#     env_file: ./.env
#     ports:
#       - "80:80"
#     depends_on:
#       DataBase:
#           condition: service_healthy
    

