name: CI/CD to Docker Hub

on:
  push:
    branches:
      - main
      - jafar
      - firas
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

      - name: Set up Docker Compose
        run: |
          docker build -t rjafarsw/real-time-chat .
          docker tag rjafarsw/real-time-chat:latest rjafarsw/real-time-chat:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push rjafarsw/real-time-chat:latest
          docker push rjafarsw/real-time-chat:${{ github.sha }}

        env:
          DOCKER_PAT: ${{ secrets.PAT }}
